### PR TITLE
adding azure support

### PR DESCRIPTION
**Pull request by PaulARoy**
I was using this amazing proxy on prod but without cache because my Azure App Service could not handle storage well enough.
But it was clearly not optimal. I thought it would be cool to add Azure Storage Support.

For that I needed an implementation of Http Cache with Azure Storage so I built one (http://github.com/PaulARoy/azurestoragecache)

This pull request only adds support for azure cache according to my package.

Usage: « -cache azure »
Three values can be passed on to the cache:
- Azure Account Name (empty = get env variable « AZURESTORAGE_ACCOUNT_NAME »)
- Azure Account Key (empty = get env variable « AZURESTORAGE_ACCESS_KEY »)
- Container Name (empty = "cache")

Feel free to modify anything. It currently runs in production for my website.

### CODE REVIEW

**Comment by PaulARoy** [comment]
Signed it

**Comment by PaulARoy** [comment]
To be honest I am not quite sure why the CI fails…
It seems related to the azure sdk package (line 183 to 194 indicates fails on azure sdk)

I tried adding my package & azure sdk to the vendors file but it did not help so far (I am quite new to Go and the whole architecture).
Does anyone have a clue on what to change? Tests seem to pass and it works in production.

**Comment by willnorris** [comment]
Hey Paul, sorry I never got around to taking a look at this when you first sent it.  Are you still interested in trying to land this?  If so, it looks like the underlying azure sdk has changed a bit since you wrote your azurestorage package.  I've never used Azure myself, so it might be faster for you to fix it up, otherwise I'll try taking a look at some point and send a pull request to your azurestorage project.

**Comment by PaulARoy** [comment]
Hi Will!
No problem for the delay.
Unfortunately I rewrote my own image proxy using Asp.Net core, I had a small issue on caching: Azure Blob Storage seem to handle incorrectly the names we use for the images (http://…)

This is my first time with Go, I tried to workaround the issue but I had to fix it quickly and rewriting the whole layer using a technology I already mastered was faster. 

I think it would be best to fix it with your project, as it is way more efficient than what I wrote.

I can work on this, but I am in a rush these weeks, I should be able to land something but not before october I think. If you prefer to work on this on your own that's fine by me.

**Comment by willnorris** [comment]
Sounds good, I'll try poking around with azure storage and see what I can figure out.  It looks like the Azure SDK has changed in relatively small ways, so I don't think it'll be a lot of work to fix your storage layer.

**Comment by willnorris** [comment]
okay, pull request sent your way: https://github.com/PaulARoy/azurestoragecache/pull/1

**Comment by willnorris** [comment]
all merged in and ready to go.  If and when you switch back to using imageproxy, let me know how it works for you.  And thanks for the contribution!

**Comment by PaulARoy** [comment]
Thank you very much! This is amazing :)

As I said I am in a rush for a few weeks but I will try as soon as I can!

**Pull request merged**
