### PR TITLE
add minio support via http

### PR DESCRIPTION
**Pull request by ruledio**
Adds minio support via HTTP,

### CODE REVIEW

**Comment by ruledio** [comment]
I signed it!

**Comment by ruledio** [comment]
I signed it!

**Comment by willnorris** [comment]
rather than add an entirely new cache, how hard would it be to modify the existing s3 implementation to support minio as well?  I've never used minio, so am not sure what additional pieces it really needs.  Can you give me an example of a minio URL?  I get that endpoint would point to your minio instance, but what value do you use for region in that case?

**Comment by willnorris** [comment]
As an example of how I was thinking we could modify the existing s3 cache, what if we pushed any of these additional config options we need into the query string?  So you could use minio with a URL such as:

    s3://{region}/{bucket}/{path}?endpoint={endpoint}&disableSSL=1&forcePathStyle=1

Or something like that?  Or are there other changes for minio that I overlooked?

**Comment by ruledio** [comment]
Not a bad shout, the reason I kept it separate was to keep things simple and not to confuse current users with changes, more than happy to take the advice and take a stab at modifying the current s3cache, I am not a heavy user of s3 or minio so I wouldn't like to comment on the forcePathStyle.

Let me know your thoughts.

**Comment by ruledio** [comment]
ok so looking at this a bit more I can see a few issues that I am not sure how to resolve, in the current URL the region is S3's endpoint, changing this behavior is more than likely going to have an impact on current users, I like the idea of using query strings but not sure how this will work.

S3: `s3://{region}/{bucket}/{path}` s3://s3-us-east-2.amazonaws.com/bucketname/images
Minio: `http://{endpoint}/{bucket}/{path}` http://minio.dev:9000/bucketname/images

Any advice here would be great.

**Comment by dvaldivia** [comment]
I'd also love to have support for minio, this PR seems to be passing everything, can it be merged?

**Comment by willnorris** [comment]
I would still much rather find a way to make these kinds of s3-compatible services work with the existing s3cache implementation, even if that means we need to make some adjustments to accommodate that.  Especially since all this seems to be doing is duplicating the s3cache with just a couple of extra options on the underlying aws.Config struct.  

I can take a quick stab at what that might look like, but don't have an easy way to test it.  I can try setting up a minio instance when I have a chance, but that may not be anytime soon.

**Comment by dvaldivia** [comment]
Thanks for the reply, is there any way I can help you with this? Running minio using docker is quite easy.

Let me know if I can help somehow

**Comment by willnorris** [comment]
Could you try testing the "s3compat" branch I just pushed and see if that works?

https://github.com/willnorris/imageproxy/tree/s3compat

**Comment by ruledio** [comment]
@willnorris this is working perfectly for me, testing with Minio.

**Comment by willnorris** [comment]
Awesome, thanks for confirming @ruledio! I'll try to get that merged into master and released later today.

**Comment by ruledio** [comment]
A quick note Minio doesn't really have regions so you have to set a fake one on the s3 URL

`s3://fake-region/bucket-name/folder-name?endpoint=minio:9000&disableSSL=1&s3ForcePathStyle=1`

**Comment by willnorris** [comment]
closing, since e860748 is now merged.

**Pull request closed without merging**
