### PR TITLE
Add points about nginx and Dockerfile

### PR DESCRIPTION
**Pull request by DenisIzmaylov**
@willnorris thank you very much for your great work!

I've wasted a few hours to get it working and find solutions in Google and issues in my CoreOS cluster  I'm sure this both points will be extra useful for other users as I mentioned here:

+ https://github.com/willnorris/imageproxy/issues/59

### CODE REVIEW

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by DenisIzmaylov** [comment]
Merge it

**Comment by willnorris** [comment]
rebased onto master and merged as 94dbd77.  thanks!

**Comment by DenisIzmaylov** [comment]
Thank you

**Pull request closed without merging**
