### PR TITLE
Add support for authorization token, now it's possible to get token f…

### PR DESCRIPTION
**Pull request by gerasghulyan**
…rom request and put in the request header to get an image of authorization required

### CODE REVIEW

**Review by armangevorgyan — APPROVED** [review]

**Comment by willnorris** [comment]
Does this really need to be per-request for your use case?  What if it were configured as a command line flag to imageproxy?  Something like:

``` sh
imageproxy -passRequestHeader X-AUTH-TOKEN
```

which would then pass along the X-AUTH-TOKEN header for all requests that have a value for that.  That would then be a bit more of a general solution that could be used for things other than auth.

**Comment by gerasghulyan** [comment]
Yes, you are right it will also work for me.
I worked with go the first time, I think I can't do it how you are
suggested.

Thanks

**Comment by willnorris** [comment]
I made a few small changes like supporting multiple headers, and merged this as d94e561.  Thanks for the contribution!

**Comment by gerasghulyan** [comment]
Cool, thank you.

**Pull request closed without merging**
