### PR TITLE
add GCS cache

### PR DESCRIPTION
**Pull request by diegomarangoni**
Add new option to cache assets on Google Cloud Storage

### CODE REVIEW

**Comment by diegomarangoni** [comment]
I signed it!

**Comment by diegomarangoni** [comment]
@willnorris do you know why my build is not passing?

**Comment by diegomarangoni** [comment]
looks like some libs are not working with Go 1.5 anymore.

**Comment by willnorris** [comment]
> looks like some libs are not working with Go 1.5 anymore.

hmm, I suspect I broke that when I upgraded the vendored packages.  :-\  As long as we're compatible with 1.8, I think we're fine though.

**Comment by diegomarangoni** [comment]
Hope it is, I am running in production lol
Serving 240GB with no problems

BTW, I didn't know how to correctly set **vendor.json**, so I leave without it.

**Comment by willnorris** [comment]
uh, wow... vendoring all the transitive dependencies brings in 57 new packages weighing about 4 MB.  More concerning is that the resulting imageproxy binary doubles in size from ~7 MB to ~14 MB.  Not your fault at all! this is just how the google cloud sdk is written.  I'm just not sure how I feel about that :-\

**Comment by diegomarangoni** [comment]
maybe writing as a plugin?
well, 14MB still considerable small for me...
may turn into a mess if the number of functionalities increases.

**Comment by willnorris** [comment]
shoving the entire JSON key into an environment variable seems a little weird, but I guess it works, and is at least consistent with the other caching backends :)  We can always adjust that later if needed.  I'll rework these commits slightly and merge shortly.

**Comment by willnorris** [comment]
well, oops.   I tried updating your branch with the updated commits and ended up breaking something which automatically closed this PR.  That was weird. In any event, everything is now merged in.

**Comment by diegomarangoni** [comment]
thanks @willnorris 
upgrading my image to latest version ;)

**Pull request closed without merging**
