### PR TITLE
Adds basic Prometheus support

### PR DESCRIPTION
**Pull request by benhaan**
New /metrics endpoint that Prometheus can scrape. Metrics provided include response times, image transformation time, remote fetch error count, and the number of requests served from cache.

I'm still new to Go, so any input/feedback on the implementation is appreciated.

### CODE REVIEW

**Comment by benhaan** [comment]
I signed it!

**Comment by alexesDev** [comment]
@benhaan this is good feature, but the branch not merged. Why?

**Comment by BrianGreenhill** [comment]
+1 for this feature :pray:

**Comment by willnorris** [comment]
Sorry for the long delay.  Merged with a few minor changes.

**Comment by BrianGreenhill** [comment]
thank you @willnorris :pray:

**Pull request closed without merging**
